AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Escola de software - Cursos - Lambda Cursos FN
Parameters:
  Environment:
    Description: Environment
    Type: String
  TableName:
    Description: Table Name
    Type: String

Resources:  
  SendEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Sender email Lambda Fn
      FunctionName: EscolaDeSoftware-Cursos-LambdaCursosFn
      Handler: app.lambdaHandler
      CodeUri: src/
      Runtime: nodejs16.x
      Timeout: 2
    Environment:
        Variables:
          TableName: !Ref TableName