AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Escola de software - Blog - Put BlogPost - Lambda Function
Parameters:
  Environment:
    Description: Environment
    Type: String
  CursosLambdaCursosPolicy:
    Description: BlogPost Table Policy
    Type: String

Resources:
  CursosLambdaCursosPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for PutObject on S3 Bucket
      ManagedPolicyName:
        !Join [
          "_",
          [!Ref Environment, "CursosLambdaCursosPolicy", "Policy"],
        ]
      Path: "/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "s3:PutObject"
            Resource: "*"

  CursosLambdaCursosFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join ["_", [!Ref Environment, CursosLambdaCursosFn]]
      Description: Lambda responsavel por buscar os cursos na base de dados
      CodeUri: src/
      Handler: EscolaDeSoftware.Cursos.LambdaCursos::EscolaDeSoftware.Cursos.LambdaCursos.Function::FunctionHandler
      Runtime: dotnet6
      Architectures:
        - x86_64
      Timeout: 5
      Policies:
        - Fn::Join:
            [
              "",
              [
                "arn:aws:iam::",
                !Sub "${AWS::AccountId}",
                ":policy/",
                !Ref CursosLambdaCursosPolicy,
              ],
            ]
