AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Escola de software - Send Email - Lambda Function

Resources:
  
  SendEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Sender email Lambda Fn
      FunctionName: EscolaDeSoftware-Cursos-LambdaCursosFn
      Handler: app.lambdaHandler
      CodeUri: src/
      Runtime: nodejs16.x
      Timeout: 2