name: Development workflow - Lambda Function
on:
  push:
    branches: [development]

jobs:
  Development-lambda-workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Restore dependencies
        run: cd src && npm install

      - name: Testing
        run: cd src && npm run test

      - name: Package
        run: |
          sam package --s3-bucket ${{ secrets.AWS_BUCKET_DEPLOY }} --template-file template.yaml --output-template-file deploy.yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Deploy
        run: |
          aws cloudformation deploy --template-file deploy.yaml --stack-name dev-escoladesoftware-cursos-lambdacursos-fn --capabilities CAPABILITY_NAMED_IAM --parameter-overrides  file://infra/dev.parameters.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

 Pull-request:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    needs: [Development-lambda-workflow]
    steps:
      - uses: actions/checkout@v2
      
      - name: Create pull request
        run: gh pr create -B main -H development --title 'Production deployment' --body 'Pull request to go to production' || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

