name: Deploy lambda - Development
on:
  push:
    branches: [development]

env:
  SOLUTION_PATH: "src/HelloWorld"
  execute_unit_tests: "false"

jobs:
  Deploy-stack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore --configuration Release

      - name: Test
        run: |
          if ${{ env.execute_unit_tests }} == true
          then
            echo "run testes"
          else
            echo "unit test skipped"
          fi

      - name: Package
        run: |
          sam package --s3-bucket ${{ secrets.AWS_BUCKET_DEPLOY }} --template-file template.yaml --output-template-file deploy.yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}


      - name: Deploy
        run: |
          aws cloudformation deploy --template-file deploy.yaml --stack-name dev-escoladesoftware-cursos-lambdacursos-fn --capabilities CAPABILITY_NAMED_IAM --parameter-overrides  file://infra/dev.parameters.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
