name: Production workflow - Lambda Function - Prod
on:
  push:
    branches: [main]

jobs:
  Deploy-lambda:
    uses: PePires58/ReusableWorkflows/.github/workflows/001_nodejs_deploy_pipeline.yaml@main
    with: 
      stack-name: "prod-escoladesoftware-cursos-lambdacursos-fn"
      parameters-file-path: "infra/prod.parameters.json"
    secrets:
      AWS_BUCKET_DEPLOY: ${{ secrets.AWS_BUCKET_DEPLOY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Update-LogGroup:
    needs: [Deploy-lambda]
    uses: PePires58/ReusableWorkflows/.github/workflows/003_cloudwatch_log_group_put_retention.yaml@main
    with: 
      log-group-name: "/aws/lambda/prod_escoladesoftware-cursos-lambdacursosfn"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}